function [fitresult, gof, std95, ir,irhigh] = createFit2(X, Y)
%CREATEFIT2(LOGWS,LMPWRTF)
%  Create a fit.
%  Data for 'untitled fit 2' fit:
%      X Input : logws
%      Y Output: lmpwrtf
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%  See also FIT, CFIT, SFIT.
%  Auto-generated by MATLAB on 20-Nov-2019 17:22:22

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( X, Y );
% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
%sse = Sum of squares due to error
%rsquare = R-squared (coefficient of determination)
%dfe = Degrees of freedom in the error
%adjrsquare =Degree-of-freedom adjusted coefficient of determination
%rmse = Root mean squared error (standard error)
resid = yData -feval(fitresult,xData);
std95 = 2*std(resid);
ir = find(abs(resid) < std95);
irhigh = find(resid < std95);
%     figure
%     plot(fitresult,xData, yData,'rs','residuals')
%     hold on
end


