function [fitresult,gof] = createFit(x, MTFCorr)
%CREATEFIT(X,MTFCORR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: MTFCorr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Oct-2019 14:21:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, MTFCorr );

% Set up fittype and options.
ft = fittype( 'rat22' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0539501186666072 0.530797553008973 0.779167230102011 0.934010684229183 0.12990620847373];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'MTFCorr vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel MTFCorr
grid on


